/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: KrStolorz (Krzysztof Stolorz) (https://sketchfab.com/KrStolorz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/1968-volkswagen-beetle-lp-f680ad7e98e445eaafed1a70f2c53911
Title: 1968 Volkswagen Beetle (LP)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
import { useFrame } from '@react-three/fiber';

export function Beetle() {
  const carRef = useRef<THREE.Group>(null!);
  const tRef = useRef(0);
  const {nodes, materials} = useGLTF('/model/beetle.glb') as any

  useFrame(() => {
    const a = 5; // scale factor for the size of the infinity symbol
    const x = a * Math.sin(tRef.current);
    const y = a * Math.sin(tRef.current) * Math.cos(tRef.current);

    if (carRef.current) {
      // Update the car position
      carRef.current.position.set(x, y, 0);

      // Make the car face the direction it's moving
      const angle = Math.atan2(y, x);
      carRef.current.rotation.z = angle + Math.PI/3;
    }

    // Increment t to animate over time
    tRef.current += 0.005;
  });

  return (
    <group
      dispose={null}
      ref={carRef}
      rotation={[0,Math.PI / 3, 0 ]}
    >
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh
        geometry={nodes.Object_7.geometry}
        material={materials.Paint}
        skeleton={nodes.Object_7.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_8.geometry}
        material={materials.Underbody}
        skeleton={nodes.Object_8.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_9.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_9.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_10.geometry}
        material={materials.Interior_dark}
        skeleton={nodes.Object_10.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_11.geometry}
        material={materials.Interior_light}
        skeleton={nodes.Object_11.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_12.geometry}
        material={materials.Reflector}
        skeleton={nodes.Object_12.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_13.geometry}
        material={materials.Glass}
        skeleton={nodes.Object_13.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_14.geometry}
        material={materials.Rubber}
        skeleton={nodes.Object_14.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_16.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_16.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_18.geometry}
        material={materials.Black_paint}
        skeleton={nodes.Object_18.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_19.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_19.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_20.geometry}
        material={materials.Rubber}
        skeleton={nodes.Object_20.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_21.geometry}
        material={materials.Reflector}
        skeleton={nodes.Object_21.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_22.geometry}
        material={materials.Black_plastic}
        skeleton={nodes.Object_22.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_24.geometry}
        material={materials.Rubber}
        skeleton={nodes.Object_24.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_25.geometry}
        material={materials.Steel}
        skeleton={nodes.Object_25.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Object_26.geometry}
        material={materials.Chrom}
        skeleton={nodes.Object_26.skeleton}
      />
    </group>
  )
}

useGLTF.preload('/model/beetle.glb')
