/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: skullgamer9456 (https://sketchfab.com/skullgamer9456)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/realistic-road-1f9ade1df2d24755b66a57bb8472a25b
Title: Realistic Road
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Road() {
  const carRef = useRef<any>();

  const {nodes, materials} = useGLTF('/model/road.glb') as any
  return (
    <group dispose={null} ref={carRef}>
      <group rotation={[-1.317, 0.079, 1.632]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-92734.32, 3226.807, 8540.379]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.RoadCut0_Road1_0.geometry}
              material={materials.Road1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Markers0_WhiteYellowDouble_4L_0.geometry}
              material={materials.WhiteYellowDouble_4L}
              position={[0, 2, 0]}
            />
          </group>
          <group position={[-88142.367, 4782.414, 27469.563]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.RoadCut1_Road1_0.geometry}
              material={materials.Road1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Markers1_WhiteYellowDouble_4L_0.geometry}
              material={materials.WhiteYellowDouble_4L}
              position={[0, 2, 0]}
            />
          </group>
          <group position={[-85384.797, 6115.249, 44324.797]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.RoadCut2_Road1_0.geometry}
              material={materials.Road1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Markers2_WhiteYellowDouble_4L_0.geometry}
              material={materials.WhiteYellowDouble_4L}
              position={[0, 2, 0]}
            />
          </group>
          <group position={[-93117.359, 6861.852, 48946.836]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.RoadCut3_Road1_0.geometry}
              material={materials.Road1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Markers3_WhiteYellowDouble_4L_0.geometry}
              material={materials.WhiteYellowDouble_4L}
              position={[0, 2, 0]}
            />
          </group>
          <group position={[-76670.227, 4415.696, 63260.09]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.RoadCut4_Road1_0.geometry}
              material={materials.Road1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Markers4_WhiteYellowDouble_4L_0.geometry}
              material={materials.WhiteYellowDouble_4L}
              position={[0, 2, 0]}
            />
          </group>
          <group position={[-83328.805, 3151.953, 77285.008]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.RoadCut5_Road1_0.geometry}
              material={materials.Road1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Markers5_WhiteYellowDouble_4L_0.geometry}
              material={materials.WhiteYellowDouble_4L}
              position={[0, 2, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/road.glb')
